// Generated by CoffeeScript 1.3.3

enchant();

window.onload = function() {
  var game;
  game = new Game(320, 320);
  game.twitterRequest("statuses/home_timeline");
  game.onload = function() {
    var tweets;
    tweets = game.twitterAssets["statuses/home_timeline"];
    return tweets.forEach(function(tweet) {
      var user;
      user = tweet.user.toSprite();
      user.scaleX = user.scaleY = 0.5 + Math.random();
      user.x = (320 - user.width) * Math.random();
      user.y = (320 - user.height) * Math.random();
      return game.rootScene.addChild(user);
    });
  };
  return game.start();
};
